### ISSUE TITLE
Release rray 0.1.0

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/rray#242]
Prepare for release: 
 
* [x] Check that description is informative 
* [x] Check licensing of included files 
* [x] `usethis::use_cran_comments()` 
* [x] `devtools::check()` 
* [x] `devtools::check_win_devel()` 
* [x] `rhub::check_for_cran()` 
* [x] `rhub::check(platform = 'ubuntu-rchk')` 
* [x] `rhub::check_with_sanitizers()` 
* [x] Polish pkgdown reference index 
* [x] ~Draft blog post~
 
Submit to CRAN: 
 
* [x] `usethis::use_version('minor')` 
* [x] Update `cran-comments.md` 
* [x] `devtools::submit_cran()` 
* [x] Approve email 
 
Wait for CRAN... 
 
* [x] Accepted :tada: 
* [ ] `usethis::use_github_release()` 
* [ ] `usethis::use_dev_version()` 
* [ ] `usethis::use_news_md()` 
* [ ] Update install instructions in README 
* [ ] Finish blog post 
* [ ] Tweet 
* [ ] Add link to blog post in pkgdown news menu

**Comment by DavisVaughan** [comment]
```
* checking installed package size ... NOTE
  installed size is 45.0Mb
  sub-directories of 1Mb or more:
    libs  44.3Mb
```

maybe add a note about this

**Comment by dirkschumacher** [comment]
I really like that checklist. Maybe this could be part of `usethis`. Create a publication checklist on github :) 🤔

**Comment by dirkschumacher** [comment]
🤯
