### ISSUE TITLE
subset behavior

### ISSUE THREAD

**Issue by kurt1984** [r-lib/rray#251]
```
library(rray)

n <- 500
n_dim <- rray(rep(n/2^12, 2^12))
dim(n_dim) <- rep(2, 12)

> dim(n_dim[pad(),1,])
 [1] 2 2 2 2 2 2 2 2 2 2 2 1
> dim(n_dim[pad(),1])
 [1] 2 2 2 2 2 2 2 2 2 2 2 1
> dim(n_dim[pad(),1,,])
 [1] 2 2 2 2 2 2 2 2 2 2 1 2

```
is this a bug? in that it need double commas to subset on the second to last dimension

**Comment by DavisVaughan** [comment]
Yea, this is definitely not right. I don't think I quite understood how subsetting should work until now. This is what the result should be.

``` r
library(rray)

n <- 500
n_dim <- rray(rep(n/2^12, 2^12))
dim(n_dim) <- rep(2, 12)

dim(n_dim[pad(),1,])
#>  [1] 2 2 2 2 2 2 2 2 2 2 1 2
dim(n_dim[pad(),1])
#>  [1] 2 2 2 2 2 2 2 2 2 2 2 1
dim(n_dim[pad(),1,,])
#>  [1] 2 2 2 2 2 2 2 2 2 1 2 2
```

<sup>Created on 2019-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

Closing this in favor of #252 which tracks the exact problem.
