### ISSUE TITLE
Add a link to the rray UseR presentation to the README

### ISSUE THREAD

**Issue by batpigandme** [r-lib/rray#255]
Or maybe a link to one of your presentations somewhere.

**Comment by DavisVaughan** [comment]
This would be a good first pull request for someone on tidy dev day. You'd need to:

- Fork the repo and clone it locally `usethis::create_from_github("r-lib/rray", destdir = "local/path/here")`
- Make a new branch for the changes `usethis::pr_init("fix-readme")`
- Update the README file to include a link to this presentation https://www.youtube.com/watch?v=LQbH5LlD7sg
   - I would add the link in the first section of the README, right before the "What can it do?" section. It would make sense to put it with the part saying: "View the vignettes for each goal on the website to learn more about how to use rray.". You could add "or watch the UseR presentation on rray", or something to that affect.
- Rerender the README.Rmd file to generate the README.md file
- Commit the changes locally
- Open the PR! `usethis::pr_push()`

**Comment by DavisVaughan** [comment]
Closed by #260
